networks:
  ai_network-01:
    driver: bridge

services:
  heygem-f2f-01:
    image: guiji2025/heygem.ai
    container_name: heygem-f2f-01
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/HeyGem/data01/face2face:/code/data
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
      - CUDA_VISIBLE_DEVICES=2
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    shm_size: '8g'
    ports:
      - '8385:8383'
    command: python /code/app_local.py
    networks:
      - ai_network-01
