networks:
  ai_network:
    driver: bridge

services:
  heygem-f2f:
    image: guiji2025/heygem.ai
    container_name: heygem-f2f
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/HeyGem.ai/data/face2face:/code/data
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
      - CUDA_VISIBLE_DEVICES=0
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    shm_size: '32g'
    ports:
      - '8383:8383'
    command: python /code/app_local.py
    networks:
      - ai_network
